#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
from pathlib import Path


RESEARCH_FILES = [
    "01-identity-biography.md",
    "02-worldview-values.md",
    "03-mental-models.md",
    "04-decision-heuristics.md",
    "05-actions-works.md",
    "06-expression-dna.md",
    "07-relational-patterns.md",
    "08-stress-conflict.md",
    "09-evolution-contradictions.md",
    "10-boundaries-unknowns.md",
]

DISTILLED_FILES = [
    "core.md",
    "heuristics.md",
    "expression.md",
    "evidence.md",
    "boundaries.md",
]


def write_if_missing(path: Path, content: str = "") -> None:
    if not path.exists():
        path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description="Create a figure skill scaffold.")
    parser.add_argument("--name", required=True, help="Figure display name")
    parser.add_argument(
        "--slug", required=True, help="Folder slug, e.g. luxun-perspective"
    )
    parser.add_argument(
        "--output-dir",
        required=True,
        help="Directory that will contain the skill folder",
    )
    args = parser.parse_args()

    skill_dir = Path(args.output_dir) / args.slug
    (skill_dir / "references" / "sources" / "raw").mkdir(parents=True, exist_ok=True)
    (skill_dir / "references" / "sources" / "cleaned").mkdir(
        parents=True, exist_ok=True
    )
    (skill_dir / "references" / "research").mkdir(parents=True, exist_ok=True)
    (skill_dir / "references" / "distilled").mkdir(parents=True, exist_ok=True)
    (skill_dir / "scripts").mkdir(parents=True, exist_ok=True)

    write_if_missing(
        skill_dir / "README.md",
        f"# {args.name}\n\nGenerated by `create-figure-skill`.\n",
    )
    write_if_missing(skill_dir / "SKILL.md")
    write_if_missing(
        skill_dir / "meta.json",
        json.dumps(
            {
                "name": args.slug,
                "title": f"{args.name} Perspective",
                "figure_name": args.name,
                "description": f"Use {args.name}'s public-information-backed lens for structured judgment.",
                "use_cases": "判断、写作、分析、批评",
                "purpose": "借助该人物的公开思维框架来分析问题，而不是做空泛模仿。",
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
    )
    write_if_missing(skill_dir / "references" / "sources" / "manifest.json", "[]\n")

    for filename in RESEARCH_FILES:
        write_if_missing(skill_dir / "references" / "research" / filename)

    for filename in DISTILLED_FILES:
        write_if_missing(skill_dir / "references" / "distilled" / filename)

    print(skill_dir)


if __name__ == "__main__":
    main()
